# A Feed Forward Multilayer Percepton Artificial Neural Network for Vector Classification

In [36]:
import numpy as np

**Initialize Network**

In [37]:
network = [3, 5, 2]

**Initialize sample data vectors and classify them**

In [38]:
initialValues = [[0.74,0.1354,0.87]]
initialValQuad = [[1,0]]
num = 0
dataSize = 100
index = 5
while (num < dataSize):
    num += 1
    ran = 1 - (2 * np.random.rand(1,3))
    initialValues = np.concatenate((initialValues,ran))
    if ran[0][2] > 0:
        initialValQuad = np.concatenate((initialValQuad,[[1,0]]), axis=0)
    else:
        initialValQuad = np.concatenate((initialValQuad,[[0,1]]), axis=0)     

**Initialize the weights and biases**

In [39]:
# This line below isn't really necessary anymore but I'm leaving it just cause, feel free to remove it or anything else
# input1 = 1-2*np.random.rand(1,network[0])
w1 = 1-2*np.random.rand(network[0],network[1])
w2 = 1-2*np.random.rand(network[1],network[2])
b1 = 1-2*np.random.rand(1,network[1])
b2 = 1-2*np.random.rand(1,network[2])

**Sigmoid Activation Function**

In [40]:
# Sigmoid function for now, once we get past function and into optimization, we could use try others like TanH, ArcTan, or even ReLU
def activate(inputs,weights,biases):
   info = np.dot(inputs,weights)-biases
   return 1 / (1 + np.exp(-info))    

**Test Code**

In [41]:
# We could change this to a while/for loop to make it customizable to the number of layers we have in our network
# the parameter could be the length(network)\
i = 0
while (i < dataSize):
    i+= 1
    networkGuess = activate(activate(initialValues[i],w1,b1),w2,b2)
    print(networkGuess)    

[[0.52458017 0.49482855]]
[[0.49865162 0.57069068]]
[[0.51569723 0.5575522 ]]
[[0.54993917 0.48490634]]
[[0.52435081 0.5073498 ]]
[[0.54532286 0.51482978]]
[[0.52241397 0.51419998]]
[[0.53934772 0.48057259]]
[[0.51831744 0.53424858]]
[[0.52405391 0.53028298]]
[[0.45394811 0.61364326]]
[[0.51252318 0.50786119]]
[[0.54777662 0.47430914]]
[[0.51640935 0.53400138]]
[[0.46653109 0.57485735]]
[[0.45781987 0.56143643]]
[[0.5065669  0.55627689]]
[[0.46242295 0.57064203]]
[[0.55422626 0.48865422]]
[[0.49306958 0.56531183]]
[[0.52209408 0.52709793]]
[[0.55515554 0.46477212]]
[[0.45901275 0.55427167]]
[[0.55764356 0.50279304]]
[[0.5427707 0.4892702]]
[[0.46107923 0.55064317]]
[[0.53131876 0.50578547]]
[[0.46508748 0.58877862]]
[[0.5200211  0.50194613]]
[[0.57683232 0.46246328]]
[[0.49453047 0.56031634]]
[[0.54421645 0.49339969]]
[[0.47295971 0.59214332]]
[[0.52344303 0.4919732 ]]
[[0.46198904 0.6006042 ]]
[[0.46686244 0.59036747]]
[[0.49267013 0.57769096]]
[[0.45480595 0.60654665]]
[[0.50707548 0